name: CI
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master
    tags:
      - '*'
env:
  FORCE_COLOR: 1
concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
        architecture:
          - x64
        node:
          - 10
          - 11
          - 12
          - 13
          - 14
          - 15
          - 16
          - 17
        include:
          - os: windows-latest
            node: 16
            architecture: x86
    name: ${{ matrix.os }} ${{ matrix.architecture }} - Node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          architecture: ${{ matrix.architecture }}

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
        if: contains(matrix.os, 'windows')
        with:
          msbuild-architecture: ${{ matrix.architecture }}

      - name: Install dependencies
        run: yarn install --ignore-scripts

      - name: Configure build
        run: yarn node-pre-gyp configure

      - name: Build binaries
        run: yarn node-pre-gyp build

      - name: Print glibc linking
        if: contains(matrix.os, 'ubuntu')
        run: |
          ldd lib/binding/*/node_sqlite3.node
          echo "---"
          nm lib/binding/*/node_sqlite3.node | grep "GLIBC_" | c++filt || true

      - name: Run tests
        run: yarn test

      - name: Package prebuilt binaries
        run: yarn node-pre-gyp package

      - name: Upload binaries to commit artifacts
        uses: actions/upload-artifact@v3
        if: matrix.node == 16
        with:
          name: prebuilt-binaries
          path: build/stage/*/*
          retention-days: 7

      - name: Upload binaries to GitHub Release
        run: yarn node-pre-gyp-github publish
        if: matrix.node == 16 && startsWith(github.ref, 'refs/tags/')
        env:
          NODE_PRE_GYP_GITHUB_TOKEN: ${{ github.token }}
  build-qemu:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' || startsWith(github.ref, 'refs/tags/')
    strategy:
      fail-fast: false
      matrix:
        node:
          - 16
        architecture:
          - linux/arm64
        variant:
          - bullseye
          - alpine
        include:
          # musl x64 builds
          - architecture: linux/amd64
            variant: alpine
            node: 16
    name: ${{ matrix.variant }} ${{ matrix.architecture }} - Node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build binaries and test
        run: |
          docker buildx build \
            --file ./tools/BinaryBuilder.Dockerfile \
            --load \
            --tag sqlite-builder \
            --platform ${{ matrix.architecture }} \
            --no-cache \
            --build-arg VARIANT=${{ matrix.variant }} \
            --build-arg NODE_VERSION=${{ matrix.node }} \
            .
          CONTAINER_ID=$(docker create -it sqlite-builder)
          docker cp $CONTAINER_ID:/usr/src/build/build/ ./build

      - name: Upload binaries to commit artifacts
        uses: actions/upload-artifact@v3
        if: matrix.node == 16
        with:
          name: prebuilt-binaries
          path: build/stage/*/*
          retention-days: 7

      - name: Upload binaries to GitHub Release
        run: yarn node-pre-gyp-github publish
        if: matrix.node == 16 && startsWith(github.ref, 'refs/tags/')
        env:
          NODE_PRE_GYP_GITHUB_TOKEN: ${{ github.token }}
