name: CI
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master
    tags:
      - '*'
env:
  FORCE_COLOR: 1
concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
        host:
          - x64
        target:
          - x64
        node:
          - 10
          - 11
          - 12
          - 13
          - 14
          - 15
          - 16
          - 17
          - 18
        include:
          - os: windows-latest
            node: 16
            host: x86
            target: x86
    name: ${{ matrix.os }} (node=${{ matrix.node }}, host=${{ matrix.host }}, target=${{ matrix.target }})
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          architecture: ${{ matrix.host }}

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
        if: contains(matrix.os, 'windows')
        with:
          msbuild-architecture: ${{ matrix.target }}

      - name: Install dependencies
        run: yarn install --ignore-scripts

      - name: Add env vars
        shell: bash
        run: |
          echo "V=1" >> $GITHUB_ENV

          if [ "${{ matrix.target }}" = "x86" ]; then
            echo "TARGET=ia32" >> $GITHUB_ENV
          else
            echo "TARGET=${{ matrix.target }}" >> $GITHUB_ENV
          fi

      - name: Add Linux env vars
        if: contains(matrix.os, 'ubuntu')
        run: |
          echo "CFLAGS=${CFLAGS:-} -include ../src/gcc-preinclude.h" >> $GITHUB_ENV
          echo "CXXFLAGS=${CXXFLAGS:-} -include ../src/gcc-preinclude.h" >> $GITHUB_ENV

      - name: Configure build
        run: yarn node-pre-gyp configure --target_arch=${{ env.TARGET }}

      - name: Build binaries
        run: yarn node-pre-gyp build --target_arch=${{ env.TARGET }}

      - name: Print binary info
        if: contains(matrix.os, 'ubuntu')
        run: |
          ldd lib/binding/*/node_sqlite3.node
          echo "---"
          nm lib/binding/*/node_sqlite3.node | grep "GLIBC_" | c++filt || true
          echo "---"
          file lib/binding/napi-v*/*

      - name: Run tests
        run: yarn test

      - name: Package prebuilt binaries
        run: yarn node-pre-gyp package --target_arch=${{ env.TARGET }}

      - name: Upload binaries to commit artifacts
        uses: actions/upload-artifact@v3
        if: matrix.node == 16
        with:
          name: prebuilt-binaries
          path: build/stage/*/*
          retention-days: 7

      - name: Upload binaries to GitHub Release
        run: yarn node-pre-gyp-github publish
        if: matrix.node == 16 && startsWith(github.ref, 'refs/tags/')
        env:
          NODE_PRE_GYP_GITHUB_TOKEN: ${{ github.token }}
  build-qemu:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' || startsWith(github.ref, 'refs/tags/')
    strategy:
      fail-fast: false
      matrix:
        node:
          - 16
        target:
          - linux/arm64
        variant:
          - bullseye
          - alpine
        include:
          # musl x64 builds
          - target: linux/amd64
            variant: alpine
            node: 16
    name: ${{ matrix.variant }} (node=${{ matrix.node }}, target=${{ matrix.target }})
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build binaries and test
        run: |
          docker buildx build \
            --file ./tools/BinaryBuilder.Dockerfile \
            --load \
            --tag sqlite-builder \
            --platform ${{ matrix.target }} \
            --no-cache \
            --build-arg VARIANT=${{ matrix.variant }} \
            --build-arg NODE_VERSION=${{ matrix.node }} \
            .
          CONTAINER_ID=$(docker create -it sqlite-builder)
          docker cp $CONTAINER_ID:/usr/src/build/build/ ./build

      - name: Upload binaries to commit artifacts
        uses: actions/upload-artifact@v3
        if: matrix.node == 16
        with:
          name: prebuilt-binaries
          path: build/stage/*/*
          retention-days: 7

      - name: Upload binaries to GitHub Release
        run: yarn install --ignore-scripts && yarn node-pre-gyp-github publish
        if: matrix.node == 16 && startsWith(github.ref, 'refs/tags/')
        env:
          NODE_PRE_GYP_GITHUB_TOKEN: ${{ github.token }}
